version: 0.1

env:
  environment: "dev"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo installing API dependencies for app-user-service
      - npm install -g serverless@3.39.0
      - echo finished installing API dependencies
      - echo copy libs files to module directory
      - cp -r libs app-user-service
      - echo finished copying libs files to module directory
      - sh libs/dependencies.sh
      - cd app-user-service
      - echo installing app-user-service API dependencies
      - npm install --silent
      - echo finished installing app-user-service API dependencies
  build:
    commands:
      - export AWS_ACCESS_KEY_ID=$KEY
      - export AWS_SECRET_ACCESS_KEY=$VALUE
      - echo deploying APIs for happ-ms-app-user-service
      - serverless deploy -s dev
      - echo finished deploying happ-ms-app-user-service
